spring:
  application:
    name: otus-architecture-hw1
  data:
    mongodb:
      uri: mongodb://otus_hw_user:12345678@${MONGO_URL}/otus_hw
      username: otus_hw_user
      password: 12345678
      database: otus_hw
      host: router-01
      port: 27017
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/hw1
    username: otus_user
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN,USER
logging:
  level:
    ROOT: debud

mq:
  login: admin
  password: ${RABBIT_PASS:dOgdFn237cd}
  host: ${RABBIT_HOST:localhost}
  port: 5672

server:
  mode: ${SERVICE_MODE:public}
  servlet:
    session:
      timeout: 10m