version: "3.8"
services:
  db:
    image: mysql
    container_name: otus-mysql-hw4
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: otus_user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hw1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=dOgdFn237cd
  social-net:
    image: edenevair/otus-hw
    platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "80:8080"
    environment:
      DB_HOST: db
      RABBIT_HOST: rabbitmq
      RABBIT_PASS: dOgdFn237cd
      SERVICE_MODEL: public
